apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - name: api
          image: <user>/library-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: library-config
